### ISSUE TITLE
add shewit communication-plan

### ISSUE THREAD

**Issue by alihaidermalik20** [lab-brussels-1/all-about-trees-2#1]
- [ ] Add availability.
- [ ] Add how many hours has per day.

**Comment by talmurshidi** [comment]
@alihaidermalik20 
Creating a separate issue for each team member is better approach and more flexible.
`One issue belongs to one PR`.
When closing the PR, the issue will be closed with it.
You can create issue for each member ex: `Tamer communication plan` and the details could be:
[/planning/communication.md](https://github.com/lab-brussels-1/all-about-trees-2/blob/master/planning/communication-plan.md)
- [ ] Add availability.
- [ ] Add how many hours has per day.
